### PR TITLE
Assume . if either stdin/on isatty() (fix #1028)

### LINKED ISSUE #1028: Redirecting or piping output has different behaviour
This caught me by surprise -- omitting the (mandatory) jq filter causes the help to be printed instead, but only if the output is redirected to a file or piped: the `.` filter is implied if redirection does not occur.

```
> echo '"x"' | ./jq -r
x
> echo '"x"' | ./jq -r > foo
jq - commandline JSON processor [version 1.5]
Usage: ./jq [options] <jq filter> [file...]
```

This is particularly mystifying if jq is invoked within a shell script, since it means the shell scripts' behaviour radically changes.

The obvious workaround is to use the `.` filter, but it's not obvious you need it when it sometimes succeeds.

I don't have a strong preference for whether it should always fail or always assume `.` as a default filter.

### PR DESCRIPTION
**Pull request by nicowilliams**
And move the #define of isatty on Windows up.

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -15,6 +15,13 @@
 #include <shellapi.h>
 #include <wchar.h>
 #include <wtypes.h>
+
+#ifdef HAVE__ISATTY
+#ifdef isatty
```
Comment (dtolnay) [inline src/main.c]: C standard says about #undef:

> It is ignored if the specified identifier is not currently defined as a macro name.

So this ifdef is redundant.

File: src/main.c [hunk 2]
```diff
@@ -15,6 +15,13 @@
 #include <shellapi.h>
 #include <wchar.h>
 #include <wtypes.h>
+
+#ifdef HAVE__ISATTY
```
Comment (dtolnay) [inline src/main.c]: This is not the same behavior as what you removed below. Below, if both are defined we replace isatty with _isatty even ifndef WIN32, but this is just for WIN32. Is that intentional?

File: src/main.c [hunk 3]
```diff
@@ -457,16 +464,8 @@ int main(int argc, char* argv[]) {
...
 
-#if (!defined(WIN32) && defined(HAVE_ISATTY)) || defined(HAVE__ISATTY)
-
-#if defined(HAVE__ISATTY) && defined(isatty)
-#undef isatty
-#define isatty _isatty
-#endif
-
-  if (!program && isatty(STDOUT_FILENO) && !isatty(STDIN_FILENO))
+  if (!program && (isatty(STDOUT_FILENO) || !isatty(STDIN_FILENO)))
```
Comment (dtolnay) [inline src/main.c]: This needs an ifdef isatty around it.

Comment (dtolnay) [inline src/main.c]: Also this is not the right condition. We want to assume "." if either one is not a tty.

File: src/main.c (hunk 2 above)
Comment (nicowilliams) [inline src/main.c]: I think so, yes :)  As in: I've never heard of `_isatty()` anywhere else.

File: src/main.c (hunk 3 above)
Comment (nicowilliams) [inline src/main.c]: Oy, I thought I pushed the correction.  I noted it in the issue.

Comment (nicowilliams) [inline src/main.c]: We didn't guard the other use of `isatty()` with an `#ifdef`.  The code assumed there's always an `isatty()`, though it might be `_isatty()`, or it might not be a `#define`, so either way we shouldn't `#ifdef isatty`, but either leave it as is or `#define` some other macro for the `#ifdef`.  Comments?

Comment (dtolnay) [inline src/main.c]: No guard then. I didn't realize this was the only guarded one.

**Comment by nicowilliams** [comment]
Oops, I squashed my fixup.
