### PR TITLE
fix: populate timezone data when formatting time

### LINKED ISSUE #1912: Wrong timezone names in strftime/strflocaltime for DST
**Describe the bug**
jq  does not print the timezone correctly expanding the %Z in the time format for strftime/strflocaltime when it comes to DST.
**To Reproduce**
Using the example from the wiki...
```
$ TZ=Europe/Rome ./jq-linux64 -cn 'now|strflocaltime("%Y-%m-%dT%H:%M:%S %Z")'
"2019-05-28T17:10:54 CET"

$ TZ=Europe/Rome date +"%Y-%m-%dT%H:%M:%S %Z"
2019-05-28T17:10:54 CEST
```
`date` reports, correctly, `CEST` as the timezone taking DST into account. `jq` does not.

**Expected behavior**
The output of `jq` to specify the correct timezone following DST

**Environment (please complete the following information):**
 - Linux Ubuntu 16.04
 - jq version 1.6

### LINKED ISSUE #2429: strflocaltime always outputs +0000 for %Z
**Describe the bug**
jq outputs wrong timezone information when using strflocaltime with the `%Z` formatter:
```
└─$ timedatectl
               Local time: So 2022-05-08 13:48:24 CEST
           Universal time: So 2022-05-08 11:48:24 UTC
                 RTC time: So 2022-05-08 11:48:24
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

└─$ jq -rn 'now | strflocaltime("%Y-%m-%dT%H:%M:%S%z")' 
2022-05-08T13:48:33+0000
```

**To Reproduce**
`TZ=Asia/Tokyo jq -rn 'now | strflocaltime("%Y-%m-%dT%H:%M:%S%z")'`
```
└─$ TZ=Asia/Tokyo jq -rn 'now | strflocaltime("%Y-%m-%dT%H:%M:%S%z")' 
2022-05-08T20:51:59+0000
```

**Expected behavior**
Output should be like the `date` command:
```
└─$ TZ=Asia/Tokyo date +"%Y-%m-%dT%H:%M:%S%z"
2022-05-08T20:51:20+0900
```

**Environment (please complete the following information):**
 - OS and Version: Linux; Reproduced on Manjaro and Debian Bullseye
 - jq version: 1.6

**Additional context**
Might be related to https://github.com/stedolan/jq/issues/1912

### LINKED ISSUE #2475: strftime uses wrong time zone for %Z
**Describe the bug**
strftime (in jq) is documented to always format times in the UTC time zone.  However, if %Z is part of the format, will be replaced with the systems local time zone, which is inconsistent with the rest of the time formatting, resulting in unexpected outputs

**To Reproduce**
$ echo '1661932759' | TZ="Europe/Zurich" jq '. | strflocaltime("%Y-%m-%dT%H:%M:%S_%Z"), strftime("%Y-%m-%dT%H:%M:%S_%Z")'
"2022-08-31T09:59:19_CET"
"2022-08-31T07:59:19_CET"

Note: the output is very misleading... the time passed in is NOT 07:59:18 *CET*

**Expected behavior**
$ echo '1661932759' | TZ="Europe/Zurich" jq '. | strflocaltime("%Y-%m-%dT%H:%M:%S_%Z"), strftime("%Y-%m-%dT%H:%M:%S_%Z")'
"2022-08-31T09:59:19_CET"
"2022-08-31T07:59:19_UTC"

Note: the second line correct shows that the printed time is in UTC

**Environment (please complete the following information):**
 - Linux Debian testing
 - jq-1.6 (Debian package version 1.6-2.1)

### PR DESCRIPTION
**Pull request by marcin-serwin**
The `jv2tm` function was zeroing fields of `struct tm` that were not specified by the standard. However, depending on the libc this produced incorrect timezone data when used together with formatting functions. This change tries to fill the timezone data using either `mktime`, `timegm`, or manually.

fixes #2475; fixes #2429; fixes #1912.

Example:
```shell
TZ=Asia/Tokyo jq -rn '1731627341 | strflocaltime("%F %T %z %Z"), strftime("%F %T %z %Z")'
```

Before:
```
2024-11-15 08:35:41 +0000 JST
2024-11-14 23:35:41 +0000 JST
```

After:
```
2024-11-15 08:35:41 +0900 JST
2024-11-14 23:35:41 +0000 GMT
```

### CODE REVIEW

**Comment by itchyny** [comment]
I'm afraid the timezone offset is not fixed even with this patch.
```
# 1.7.1
 $ TZ=Asia/Tokyo jq -rn '1731627341 | strflocaltime("%F %T %z %Z"), strftime("%F %T %z %Z")'  
2024-11-15 08:35:41 +0900 JST
2024-11-14 23:35:41 +0900 JST

# marcin-serwin:strftime-fix
 $ TZ=Asia/Tokyo ./jq -rn '1731627341 | strflocaltime("%F %T %z %Z"), strftime("%F %T %z %Z")'
2024-11-15 08:35:41 +0900 JST
2024-11-14 23:35:41 +0900 UTC

# 1.7.1
 $ TZ=Europe/Paris jq -rn '1731627341 | strflocaltime("%F %T %z %Z"), strftime("%F %T %z %Z")'
2024-11-15 00:35:41 +0100 CET
2024-11-14 23:35:41 +0100 CET

# marcin-serwin:strftime-fix
 $ TZ=Europe/Paris ./jq -rn '1731627341 | strflocaltime("%F %T %z %Z"), strftime("%F %T %z %Z")'
2024-11-15 00:35:41 +0100 CET
2024-11-14 23:35:41 +0100 UTC

 $ uname -v
Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
```

**Comment by marcin-serwin** [comment]
This issue is caused by a bug in the Apple's Libc implementation. Specifically in [this line](https://github.com/apple-oss-distributions/Libc/blob/Libc-1669.40.2/stdtime/FreeBSD/strftime.c#L507) the `__DARWIN_UNIX03` macro is negated which means that the `strftime` is ignoring the time offset data present in the `tm struct` in favor of the older heuristic needed by legacy standards. Looking at other uses of this macro, it seems to enable non-legacy behavior so the negation here is likely a bug since this means that the presence of this macro opts into the legacy behavior. The FreeBSD libc, from which the Apple's one is forked, does not have this issue.

I've added a workaround in the second commit that temporarily sets the global timezone to UTC if it is compiled for apple platforms.

**Comment by wader** [comment]
Nice digging 👍 jq can be used as a library does that make it a bad idea to use `setenv`? 🤔 

Possible to add some tests for this?

**Comment by marcin-serwin** [comment]
> jq can be used as a library does that make it a bad idea to use `setenv`? 🤔

`setenv` is already used in the `my_mktime` function for a similar purpose. It can cause issues in multi-threaded programs but I don't know how to avoid that.

> Possible to add some tests for this?

I've added some tests in `tests/shtest`, is this the right place?

**Comment by marcin-serwin** [comment]
I've disabled the tests on windows. The ucrt on Windows always uses the global settings for determining the timezone, which is documented in a note near the end of [the strftime docs](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-170). I tried to make them work similarly to Apple workaround by using `setenv` and `_tzset` but I couldn't make it work and I gave up trying to figure out why. Given that it's a documented behavior for Windows and the `jq` docs warn that `strftime` output depends on the operating system I think it's ok to leave it as is.

**Comment by wader** [comment]
> > jq can be used as a library does that make it a bad idea to use `setenv`? 🤔
> 
> `setenv` is already used in the `my_mktime` function for a similar purpose. It can cause issues in multi-threaded programs but I don't know how to avoid that.

I see 👍

> > Possible to add some tests for this?
> 
> I've added some tests in `tests/shtest`, is this the right place?

Is fine i think

About the apple libc bug: Will things break once/if apple fix it?

Otherwise i think this looks fine but would be great with some more eyes on it

**Comment by marcin-serwin** [comment]
> About the apple libc bug: Will things break once/if apple fix it?

It will still work. With this bug fixed, the code will ignore the `TZ` variable and just look inside the struct for the timezone thus behaving like glibc.

**Review by itchyny — COMMENTED** [review]
I think this is okay to merge, but sorry for shtest conflict.

**Review by itchyny — APPROVED** [review]
LGTM, thank you.

File: src/builtin.c [hunk 1]
```diff
@@ -1740,13 +1752,27 @@ static jv f_strftime(jq_state *jq, jv a, jv b) {
...
     return ret_error(b, jv_string("strftime/1 requires parsed datetime inputs"));
 
   const char *fmt = jv_string_value(b);
   size_t alloced = strlen(fmt) + 100;
   char *buf = alloca(alloced);
+#ifdef __APPLE__
+  /* Apple Libc (as of version 1669.40.2) contains a bug which causes it to
+   * ignore the `tm.tm_gmtoff` in favor of the global timezone. To print the
+   * proper timezone offset we temporarily switch the TZ to UTC. */
+  char *tz = getenv("TZ");
```
Comment (itchyny) [inline src/builtin.c:1765]: @marcin-serwin 
Oh, we have to copy the string (just like how `my_mktime` does), otherwise we end up failing to restore `TZ`.
See the following code.
```cpp
#include <stdio.h>
#include <stdlib.h>

int main(void) {
  // Set to UTC and restore.
  char *tz = getenv("TZ");
  printf("%s\n", tz); // Etc/GMT+7
  setenv("TZ", "UTC", 1);
  printf("%s\n", tz); // Etc/GMT+7
  setenv("TZ", tz, 1);

  // Set to UTC and try to restore but fail.
  tz = getenv("TZ");
  printf("%s\n", tz); // Etc/GMT+7
  setenv("TZ", "UTC", 1);
  printf("%s\n", tz); // UTC (expected)
  setenv("TZ", tz, 1);

  tz = getenv("TZ");
  printf("%s\n", tz); // UTC
}
```
```sh
 $ TZ=Etc/GMT+7 ./a.out
Etc/GMT+7
Etc/GMT+7
Etc/GMT+7
UTC
UTC
```
This failure appears in the following interesting jq query (of course on macOS).
```sh
 $ TZ=Etc/GMT+7 ./jq -nc '1731627341 | .,. | [strftime("%FT%T"),strflocaltime("%FT%T%z")]'
["2024-11-14T23:35:41","2024-11-14T16:35:41-0700"]
["2024-11-14T23:35:41","2024-11-14T23:35:41+0000"]
```

Comment (marcin-serwin) [reply src/builtin.c:1765]: You're right, I've opened https://github.com/jqlang/jq/pull/3264 with the fix.
