### PR TITLE
Pre-allocate tokenbuf for string parser

### LINKED ISSUE #3483: UB in string parsing logic (`src/jv_parse.c`)
**Describe the bug**
I believe I have found an undefined behavior bug in the parsing logic. Parsing any JSON containing an empty string (`""`) triggers null pointer arithmetic in `found_string()` at `src/jv_parse.c:449`.

**To Reproduce**
Build with UBSan and run:

```bash
$ echo -n '"",2,3]' | ./jq '.'
src/jv_parse.c:449:27: runtime error: applying zero offset to null pointer
    #0 0x55bebbcc0a6e in found_string /tmp/tmp.tfxMptXlGv/jq/src/jv_parse.c:449:27
    #1 0x55bebbcc0a6e in scan /tmp/tmp.tfxMptXlGv/jq/src/jv_parse.c:695:7
    #2 0x55bebbcc0a6e in jv_parser_next /tmp/tmp.tfxMptXlGv/jq/src/jv_parse.c:796:11
    #3 0x55bebbcc8f94 in jq_util_input_next_input /tmp/tmp.tfxMptXlGv/jq/src/util.c:434:15
    #4 0x55bebbca2b02 in main /tmp/tmp.tfxMptXlGv/jq/src/main.c:671:34
    #5 0x7f7cc6e2a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #6 0x7f7cc6e2a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #7 0x55bebbc76bd4 in _start (/tmp/tmp.tfxMptXlGv/jq/jq+0x88bd4) (BuildId: 8b5aea643d6e2cd9df61b76b5e82b9a4e9486523)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/jv_parse.c:449:27 
```

<details>
<summary>Script to reproduce</summary>

```bash
#!/bin/bash
set -e
git clone --depth 1 https://github.com/jqlang/jq.git
cd jq
git submodule update --init
autoreconf -fi
CC=clang \
  CFLAGS="-g -O1 -fsanitize=undefined -fno-sanitize-recover=all" \
  LDFLAGS="-fsanitize=undefined" \
  ./configure --disable-shared --with-oniguruma=builtin --silent
make -j"$(nproc)" --silent
echo -n '"",2,3]' > input.json
UBSAN_OPTIONS=print_stacktrace=1 ./jq '.' input.json 2>&1
```

</details>

**Expected behavior**
No crash

**Environment (please complete the following information):**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.3 LTS
Release:        24.04
Codename:       noble
$ uname -r
6.8.0-87-generic
$ ./jq/jq --version  
jq-master-b33a763-dirty
```

**Additional context**
My understanding is the following: In `found_string()`, the token buffer pointers are derived from `p->tokenbuf`:

```c
char* in = p->tokenbuf;
char* out = p->tokenbuf;
char* end = p->tokenbuf + p->tokenpos;  // line 449 -- UB here
```

For empty strings `""`, the parser transitions through `QUOTE` -> `JV_PARSER_STRING` -> closing `QUOTE` -> `found_string()` without ever calling `tokenadd()`. Since `tokenadd()` is the only function that allocates `tokenbuf`, both `tokenbuf` (NULL) and `tokenpos` (0) retain their initial values from `parser_init()`. The expression `NULL + 0` is undefined behavior.

I assume that the tokenpos can be used to check if the string body is empty. A short-circuit for empty strings before any pointer arithmetic is performed should fix this:

```diff
 static pfunc found_string(struct jv_parser* p) {
+  if (p->tokenpos == 0) {
+    TRY(value(p, jv_string("")));
+    return 0;
+  }
   char* in = p->tokenbuf;
   char* out = p->tokenbuf;
   char* end = p->tokenbuf + p->tokenpos;
```

If this looks good, I can create a PR for this patch.

Note: I found this bug using [Atlantis](https://github.com/Team-Atlanta/aixcc-afc-atlantis) as well

### PR DESCRIPTION
**Pull request by fab1ano**
Fixes #3483

### CODE REVIEW

**Review by wader — APPROVED** [review]

**Comment by itchyny** [comment]
This seems to happen only when the buffer is not allocated yet, but found_string is called for every string and this branch is rarely matched in practice. How about pre-allocate the buffer on init? Maybe with size 256?

**Comment by wader** [comment]
> This seems to happen only when the buffer is not allocated yet, but found_string is called for every string and this branch is rarely matched in practice. How about pre-allocate the buffer on init? Maybe with size 256?

Yes, i for some reason thought the token buffer wasn't reused but now i see reset only change the pos to zero. Then i agree per-allocate is probably better.

btw i noticed a `p->tokenbuf = 0` that confusd me a bit, change to `NULL`?

**Comment by fab1ano** [comment]
I changed this to pre-allocate instead of the size check. Let me know if this looks good and I can rebase + squash if you want.

File: src/jv_parse.c [hunk 1]
```diff
@@ -79,8 +79,9 @@ static void parser_init(struct jv_parser* p, int flags) {
   p->last_seen = JV_LAST_NONE;
   p->output = jv_invalid();
   p->next = jv_invalid();
-  p->tokenbuf = 0;
```
Comment (wader) [inline src/jv_parse.c:82]: nice to get rid of this, annoyed me :)

**Review by wader — APPROVED** [review]
👍 

Separate to this: i wonder if we should add a sanitize build to the CI?

**Comment by itchyny** [comment]
Change the PR title, please.

**Comment by fab1ano** [comment]
Sorry, I missed that. Changed now!

**Comment by wader** [comment]
Thanks!
